urls.py
# Copyright 2014 University of Alaska Anchorage Experimental Economics
# Laboratory
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('banking.views',

        # Views for the "banking" experiment type
        url(r'^$', 'index', name='index'),
        url(r'^participate/?$', 'participant_index', name='participant_index'),
        url(r'^experiment/?$', 'experimenter_index', name='experimenter_index'),

        # Views for a specific experiment
        url(r'^(?P<experiment_id>\d+)/experimenter$', 'experimenter',
            name='experimenter'),
        url(r'^(?P<experiment_id>\d+)/set_visibility$', 'set_visibility',
            name='set_visibility'),
        url(r'^(?P<experiment_id>\d+)/configure$', 'configure',
            name='configure'),
        url(r'^(?P<experiment_id>\d+)/allocate-groups$', 'allocate_groups',
            name='allocate_groups'),
        url(r'^(?P<experiment_id>\d+)/remove-participant$', 'remove_participant',
            name='remove_participant'),
        url(r'^(?P<experiment_id>\d+)/advance$', 'advance',
            name='advance'),
        url(r'^(?P<experiment_id>\d+)/reset$', 'reset',
            name='reset'),
        url(r'^(?P<experiment_id>\d+)/download-data$', 'download_data',
            name='download_data'),
        url(r'^(?P<experiment_id>\d+)/email-data$', 'email_data',
            name='email_data'),
        url(r'^(?P<experiment_id>\d+)/participate$', 'participate',
            name='participate'),
        url(r'^(?P<experiment_id>\d+)/submit-decision$', 'submit_decision',
            name='submit_decision'),
        url(r'^(?P<experiment_id>\d+)/timer_expiration$', 'timer_expiration',
            name='timer_expiration'),

        # Clock synchronization
        url(r'^gettime$', 'gettime', name='gettime'),

        # Test URLs
        url(r'^participate-test/?$', 'participate_test'),
        url(r'^server-clock/?$', 'server_clock'),
        )

models.py
# Copyright 2014 University of Alaska Anchorage Experimental Economics
# Laboratory
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import time
from decimal import Decimal

from django.db import models

from vcweb.core import signals, simplecache
from vcweb.core.models import ExperimentMetadata, Experiment,\
        ParticipantGroupRelationship

@simplecache
def get_experiment_metadata(refresh=False):
    return ExperimentMetadata.objects.get(namespace='banking')

def set_test_timer(seconds):
    state = ExperimentState.objects.get(experiment__isnull=True)
    now_ms = int(time.time() * 1000)
    state.timer_expiration = int((time.time() + seconds) * 1000)
    state.save()

class RoundParameterSet(models.Model):
    """
    The set of parameters for a specific round of a specific experiment
    """

    TIME_LIMIT_CHOICES = (
            (5, '5 sec'),
            (30, '30 sec'),
            (60, '1 min'),
            (120, '2 min'),
            (180, '3 min'),
            )

    experiment = models.ForeignKey(Experiment)
    round_number = models.PositiveIntegerField()

    practice = models.BooleanField(
            default=False,
            help_text="Make this a practice round " +
            "(equity will not be added to total earnings)")
    hedging = models.BooleanField(
            default=False,
            help_text="Incorporate hedging with interbank deposits")
    period_1_deposit_time_limit = models.PositiveIntegerField(
            choices=TIME_LIMIT_CHOICES, default=60,
            help_text="Time limit (seconds) for deposit decision in Period 1")
    period_1_lending_time_limit = models.PositiveIntegerField(
            choices=TIME_LIMIT_CHOICES, default=60,
            help_text="Time limit (seconds) for lending decision in Period 1")
    period_2_time_limit = models.PositiveIntegerField(
            choices=TIME_LIMIT_CHOICES, default=60,
            help_text="Time limit (seconds) for Period 2")
    period_3_time_limit = models.PositiveIntegerField(
            choices=TIME_LIMIT_CHOICES, default=60,
            help_text="Time limit (seconds) for Period 3")
    impatient_withdrawals = models.IntegerField(
            default=25,
            help_text="Total withdrawals by impatient depositors " +
            "in period 2 in the \"normal\" economy")
    complementarity = models.BooleanField(default=True,
            help_text="If True (checked), the \"Impatient withdrawals\" "
            "parameter defines the number of impatient depositors in the "
            "region with the \"normal\" economy. That region is selected "
            "randomly, and the other region has the \"recession\" economy with "
            "impatient depositors equal to 100 minus withdrawals in the first "
            "region. If set to False (unchecked), a random draw determines "
            "whether both regions have the \"normal\" economy, or both have "
            "the \"recession\" economy.  If both are \"normal\", they have a "
            "number of impatient depositors equal to the \"Impatient "
            "withdrawals\" parameter. If both are \"recession\", they have a "
            "number of impatient depositors equal to 100 minus the \"Impatient "
            "withdrawals\" parameter.")
    deposit_interest_rate = models.DecimalField(
            default=Decimal('0.25'),
            max_digits=3, decimal_places=2,
            help_text="Interest rate for patient depositors")
    loan_interest_rate = models.DecimalField(
            default=Decimal('0.5'),
            max_digits=3, decimal_places=2,
            help_text="Interest rate for mature loans")
    bank_interest_rate = models.DecimalField(
            default=Decimal('0.25'),
            max_digits=3, decimal_places=2,
            help_text="Interest rate for patient interbank deposits")
    loan_price = models.DecimalField(
            default=Decimal('0.4'),
            max_digits=3, decimal_places=2,
            help_text="Price of loans sold in period 2")

    class Meta:
        unique_together = ('experiment', 'round_number')
        ordering = unique_together

class ExperimentState(models.Model):
    """
    Represents the current state of a specific experiment
    """

    # If null, this is the ExperimentState used by participate-test
    experiment = models.OneToOneField(Experiment, null=True, blank=True)

    round_number = models.PositiveIntegerField()
    period_number = models.PositiveIntegerField()
    subperiod = models.CharField(
            null=True, blank=True,
            max_length=20,
            choices=(('deposit', 'deposit'), ('lending', 'lending')))

    # The time at which the period timer will expire, measured in milliseconds
    # since the Unix Epoch (corresponding to JavaScript's Date.getTime())
    timer_expiration = models.BigIntegerField(null=True, blank=True)

    @property
    def ms_remaining(self):
        if self.timer_expiration is None:
            return 0
        else:
            return max(0, self.timer_expiration - int(time.time() * 1000))

    @property
    def period_display_number(self):
        if self.period_number == 1 and self.subperiod is not None:
            if self.subperiod == 'deposit':
                return '1A: deposit decision'
            else:
                return '1B: lending decision'
        else:
            return str(self.period_number)

    def set_timer_sec(self, seconds):
        self.timer_expiration = int((time.time() + seconds) * 1000)

class PeriodData(models.Model):
    """
    Represents information about a specific participant in a specific experiment
    during a specific round and period. Each row in the main output file
    corresponds to one model instance
    """

    participant_group_relationship = models.ForeignKey(
            ParticipantGroupRelationship)
    round_number = models.PositiveIntegerField()
    period_number = models.PositiveIntegerField()

    cash = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    onDepositAtOtherBank = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    loans = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    deposits = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    depositFromOtherBank = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    borrowings = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    depositDecision = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    lendingDecision = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    withdrawals = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    recalledByOtherBank = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    totalOwed = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    paidFromCash = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    paidFromRecalledFunds = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    loansSold = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    paidFromLoans = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    paidFromBorrowing = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    withdrawalByOtherBank = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    bankPayoff = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    loanPayoff = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    earnings = models.DecimalField(
            null=True, max_digits=9, decimal_places=2)
    economy = models.CharField(
            null=True, max_length=20)

    @property
    def equity(self):
        return ((self.cash + self.onDepositAtOtherBank + self.loans)
                - (self.deposits + self.depositFromOtherBank + self.borrowings))

    @property
    def group_number(self):
        return self.participant_group_relationship.group_number

    @property
    def bank_number(self):
        return self.participant_group_relationship.participant_number

    @property
    def region_number(self):
        return (self.bank_number - 1) % 2 + 1

    @property
    def depositee_number(self):
        """ The bank_number of this bank's depositee bank """
        return (self.bank_number %
                self.participant_group_relationship.group.size
                + 1)

    @property
    def depositor_number(self):
        """ The bank_number of this bank's depositor bank """
        return ((self.bank_number - 2)
                % self.participant_group_relationship.group.size
                + 1
                )

    class Meta:
        unique_together = (
                'participant_group_relationship',
                'round_number',
                'period_number')
        ordering = ('round_number', 'period_number')

templates/banking/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Banking Experiment 1.0{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{STATIC_URL}}jquery.mobile-1.3.1/jquery.mobile-1.3.1.min.css" />
        <script src="{{STATIC_URL}}js/jquery-1.9.1.min.js"></script>
        <script src="{{STATIC_URL}}jquery.mobile-1.3.1/jquery.mobile-1.3.1.min.js"></script>
        <script type="text/javascript">
            {# used by NTP.js #}
            var gettime_url = "{% url 'banking:gettime' %}";

            {# used by timer.js: updateTimer() #}
            var timer_expiration = {{ state.timer_expiration|default:0 }};
            var timer_expiration_url = "{% url 'banking:timer_expiration' experiment_id=experiment.id %}";
            var round_number = {{ state.round_number|default:1 }};
            var period_number = {{ state.period_number|default:1 }};
            var num_rounds = {{ num_rounds|default:0 }};
        </script>
        <script type="text/javascript" src="{{STATIC_URL}}js/NTP.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/timer.js"></script>
        {% block extrahead %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/banking/configure.html
{% extends "banking/base.html" %}

{% load admin_urls %}

{% block extrahead %}
    <style type="text/css">
        .ui-block-a .grid-cell, .ui-block-b .grid-cell {
            margin-right: 1em;
        }
    </style>
{% endblock %}

{% block body %}

<div id="page" data-role="page">

    <div data-role="header">
        Banking Experiment 1.0 - Edit Parameters
    </div>

    <div data-role="content">

        <form id="parameters_form" method="post" action="" data-ajax="false">
            {{ formset.management_form }}
    
            {% for form in formset %}
                {{ form.id }}
                <div class="ui-grid-b">
                    <div class="ui-block-a">
                        <div class="grid-cell">
                            <h2>Round {{form.instance.round_number|default:''}}</h2>
                            <label>
                                Delete
                                {{ form.DELETE }}
                            </label>
                            <fieldset data-role="controlgroup">
                                <label>Practice {{form.practice }}</label>
                                <label>Hedging {{form.hedging }}</label>
                                <label>Complementarity {{form.complementarity }}</label>
                            </fieldset>
                            <table>
                                <tr><td>Impatient withdrawals</td><td>{{form.impatient_withdrawals }}</td></tr>
                            </table>
                        </div>
                    </div>
                    <div class="ui-block-b">
                        <div class="grid-cell">
                            <h3>Time Limits</h3>
                            <table>
                                <tr><td>Period 1 deposit</td><td>{{form.period_1_deposit_time_limit}}</td></tr>
                                <tr><td>Period 1 lending</td><td>{{form.period_1_lending_time_limit}}</td></tr>
                                <tr><td>Period 2</td><td>{{form.period_2_time_limit}}</td></tr>
                                <tr><td>Period 3</td><td>{{form.period_3_time_limit}}</td></tr>
                            </table>
                        </div>
                    </div>
                    <div class="ui-block-c">
                        <div class="grid-cell">
                            <h3>Rates</h3>
                            <table>
                                <tr><td>Deposit interest</td><td>{{form.deposit_interest_rate}}</td></tr>
                                <tr><td>Loan interest</td><td>{{form.loan_interest_rate}}</td></tr>
                                <tr><td>Bank interest</td><td>{{form.bank_interest_rate}}</td></tr>
                                <tr><td>Loan price</td><td>{{form.loan_price}}</td></tr>
                            </table>
                        </div>
                    </div>
                </div>
                <hr/>
            {% endfor %}


            {% comment %}
            <table>
                {% for form in formset %}

                    {% if forloop.first %}
                        <thead>
                            <tr>
                                <th>Round</th>
                                {% for field in form.visible_fields %}
                                    <th>{{ field.label|capfirst }}</th>
                                {% endfor %}
                            </tr>
                        </thead>
                    {% endif %}

                    <tr>
                        {{ form.id }}
                        <td>{{form.instance.round_number|default:''}}</td>
                        {% for field in form.visible_fields %}
                            <td>{{ field }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            {% endcomment %}




            <div class="ui-grid-b">
                <span class="ui-block-a">
                    <a data-role="button" href="{% url 'banking:experimenter' experiment_id=experiment.id %}">Cancel</a>
                </span>
                <span class="ui-block-b">
                    <input type="submit" value="Save" data-theme="b"/>
                </span>
                <span class="ui-block-c">
                    <input type="submit" name="add_round" value="Save and Add Round" data-theme="b"/>
                </span>
            </div>
        </form>

    </div>
</div>

{% endblock %}

templates/banking/experimenter-index.html
{% extends "experimenter/base.html" %}

{% block title %} Testexp Experimenter Interface {% endblock %}

{% block content %}
<h3>Manage your experiments</h3>
<p>
<ul>
{% for experiment in experiments %}
    <li class='experiment'><a href='{{ experiment.management_url }}'>{{ experiment }}</a></li>
{% endfor %}
</ul>

</p>


{% endblock content %}

templates/banking/experimenter.html
{% extends "banking/base.html" %}

{% load admin_urls %}
{% load url from future %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/experimenter.css?v=2"/>
<script type="text/javascript" src="{{STATIC_URL}}js/experimenter.js?v=2"></script>
{% endblock %}

{% block body %}

<div id="page" data-role="page">

    <div data-role="header">
        Banking Experiment 1.0 Experimenter Interface
    </div>

    <div data-role="content">

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <table id="visibility-table">
            <tbody>
                <tr>
                    <th>Visibility:</th>
                    <td>
                        {% if experiment.is_visible %}
                            Visible
                        {% else %}
                            Hidden
                        {% endif %}
                    </td>
                    <th>Authentication Code:</th>
                    <td>
                        {% if experiment.authentication_code %}
                            {{ experiment.authentication_code }}
                        {% else %}
                            <i>none</i>
                        {% endif %}
                    </td>
                    <td>
                        <a href="#" id="visibility-change-link">Change</a>
                    </td>
                </tr>
            </tbody>
        </table>

        <form id="visibility-form" style="display: none" data-ajax="false" action="set_visibility" method="post">
            <table>
                <tbody>
                    <tr>
                        <th>Visibility:</th>
                        <td>
                            <fieldset data-role="controlgroup" data-type="horizontal">
                                <label>
                                    Hidden
                                    <input type="radio" name="is_visible" value="0"
                                    {% if not experiment.is_visible %} checked="checked" {% endif %} />
                                </label>
                                <label>
                                    Visible
                                    <input type="radio" name="is_visible" value="1"
                                    {% if experiment.is_visible %} checked="checked" {% endif %} />
                                </label>
                            </fieldset>
                        </td>
                        <th>Authentication Code:</th>
                        <td>
                            <input type="text" name="authentication_code" value="{{experiment.authentication_code}}" placeholder="Anyone can join"/>
                        </td>
                        <td>
                            <a data-role="button" id="visibility-cancel-button" data-inline="true" data-icon="delete">Cancel</a>
                            <input type="submit" data-inline="true" data-theme="b" data-icon="check" value="Save"/>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>

        <h1>Experiment Status</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Group Size</th>
                    <th>Round</th>
                    <th>Period</th>
                    <th>Time Remaining</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{experiment.id}}</td>
                    <td>{{experiment.experiment_configuration.max_group_size}}</td>
                    {% if state %}
                    <td>{{state.round_number}}</td>
                    <td>{{state.period_display_number}}</td>
                    <td class="timer"></td>
                    {% else %}
                    <td colspan="3">The experiment has not started yet.</td>
                    {% endif %}
                </tr>
            </tbody>
        </table>

        <form id="advance_form" method="post" action="advance" data-ajax="false" class="ui-grid-a">
            {% csrf_token %}
            <div class="ui-block-a">
                <input type="submit" id="advance_button" value="Advance to Next Period"/>
            </div>
            <div class="ui-block-b">
                <label for="auto_advance">Auto-advance</label>
                {% if request.session.auto_advance %}
                    <input type="checkbox" id="auto_advance" name="auto_advance" checked="checked"/>
                {% else %}
                    <input type="checkbox" id="auto_advance" name="auto_advance"/>
                {% endif %}
            </div>
        </form>
        <form id="reset-experiment-form" method="post" action="reset" data-ajax="false">
            {% csrf_token %}
            <input type="submit" value="Reset Experiment">
        </form>

        <h1>Participant Status</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Group</th>
                    <th>Bank</th>
                    <th>Region</th>
                    <th>Deposit Decision</th>
                    <th>Lending Decision</th>
                    <th>Total Earnings</th>
                    <th></th> {# Remove button #}
                </tr>
            </thead>
            <tbody>
                {% for row in participant_status_table %}
                <tr>
                    <td>{{row.participant.id}}
                        <span style="display: none" class="participant_str">{{row.participant}}</span>
                    </td>
                    <td>{{row.participant.full_name}}</td>
                    <td>{{row.participant.email}}</td>
                    <td>{{row.group_number}}</td>
                    <td>{{row.bank_number}}</td>
                    <td>{{row.region_number}}</td>
                    <td>{{row.depositDecision}}</td>
                    <td>{{row.lendingDecision}}</td>
                    <td>{{row.earnings}}</td>
                    <td>
                        <form method="post" action="remove-participant" data-ajax="false">
                            <input type="hidden" name="participant_id" value="{{row.participant.id}}"/>
                            <input type="submit" value="Remove" data-mini="true" data-icon="delete"/>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <form method="post" action="allocate-groups" data-ajax="false">
            <input type="submit" value="Allocate Groups"/>
        </form>

        <h1>Round Parameters</h1>

        <a data-role="button" data-ajax="false" href="{% url 'banking:configure' experiment.id %}">Edit Parameters</a>

        <h2><a data-ajax="false" href="{% url 'banking:download_data' experiment_id=experiment.id %}">Download Data</a></h2>

        <h2>Email Data</h2>
        <form method="post" action="{% url 'banking:email_data' experiment_id=experiment.id %}" data-ajax="false">
            <div class="ui-grid-a">
                <div class="ui-block-a">
                    <input type="text" name="recipient" value="{{request.user.email}}"/>
                </div>
                <div class="ui-block-b">
                    <input type="submit" value="Send"/>
                </div>
            </div>
        </form>

    </div> <!-- /content -->

</div>

{% endblock %}

templates/banking/participant-index.html
{% extends "participant/base.html" %}

{% block title %}Test Experiment{% endblock %}

{% block page %}
<div class='info'>
    Welcome back, {{ request.user.participant }}.
</div>
<h3>{{experiment.namespace|title}} Experiments</h3>
<div class='notice'>
    {% for experiment_status, experiments in experiment_dict.items %}
    <h3> {{ experiment_status|title }} </h3>
    <ul id='experiments'>
        {% for experiment in experiments %}
        <li class='{{experiment_status|lower}}'> <a href='{{ experiment.participant_url }}'>{{ experiment.status_line }}</a></li>
        {% empty %}
        <li class='alert'> No {{ experiment_status }} experiments </li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endblock %}


templates/banking/server-clock.html
{% extends 'banking/base.html' %}

{% block title %}Server Clock{% endblock %}

{% block extrahead %}
    <script src="{{STATIC_URL}}js/jquery-1.9.1.min.js"></script>
<script type="text/javascript">
    var gettime_url = "{% url 'banking:gettime' %}";
</script>
<script type="text/javascript" src="{{STATIC_URL}}js/NTP.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        setInterval(updateTimer, 250);
    });

    function updateTimer() {
        
        // Get the current time, NTP-corrected (see NTP.js)
        var curTime = new Date();
        curTime = new Date(NTP.fixTime(curTime.getTime()));

        $('#clock').text(curTime.toTimeString());
    }
        
</script>
{% endblock %}

{% block body %}

<h1 id="clock">
</h1>

{% endblock %}